// routes/index.js
import express from "express";
import authRoutes from "./auth.routes.js";
import eventRoutes from "./event.routes.js";
import clientRoutes from "./client.routes.js";
import partnerRoutes from "./partner.routes.js";
import paymentRoutes from "./payment.routes.js";
import financeRoutes from "./finance.routes.js";
import taskRoutes from "./task.routes.js";
import reminderRoutes from "./reminder.routes.js";
import roleRoutes from "./role.routes.js";
import teamRoutes from "./team.routes.js";
import venueRoutes from "./venue.routes.js";
import userRoutes from "./user.routes.js";
import uploadRoutes from "./uploadRoutes.js";
import invoiceRoutes from "./invoices.routes.js";
import invoiceSettingsRoutes from "./invoiceSettingsRoutes.js";
import contractRoutes from "./contract.routes.js";
import supplyRoutes from "./supply.routes.js";
import supplyCategoryRoutes from "./supplyCategory.routes.js";
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/events", eventRoutes);
router.use("/clients", clientRoutes);
router.use("/partners", partnerRoutes);
router.use("/payments", paymentRoutes);
router.use("/finance", financeRoutes);
router.use("/tasks", taskRoutes);
router.use("/reminders", reminderRoutes);
router.use("/roles", roleRoutes);
router.use("/team", teamRoutes);
router.use("/venues", venueRoutes);
router.use("/upload", uploadRoutes);
router.use("/users", userRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/invoices/settings", invoiceSettingsRoutes);
router.use("/contracts", contractRoutes);
router.use("/supplies", supplyRoutes);
router.use("/supply-categories", supplyCategoryRoutes);
export default router;